#!/usr/bin/env python3
"""Generate missing player profile pages using the Dinesh Kharel page as a template."""

from __future__ import annotations

import json
import re
from pathlib import Path
from typing import Any
from urllib.parse import quote

from bs4 import BeautifulSoup


ROOT = Path(__file__).resolve().parent.parent
PLAYERS_DIR = ROOT / "players"
TEAMS_DIR = ROOT / "teams"
IMAGES_DIR = ROOT / "images" / "players"
TEMPLATE_PATH = PLAYERS_DIR / "dinesh-kharel.html"
SITE_URL = "https://nplcricketleague.com"
GENERATED_MARKER = "<!-- Generated by scripts/generate_missing_player_profiles.py -->"
SUBTITLE = "NPL 2026 Profile, Stats, and Career Insights"
DEFAULT_IMAGE = "/images/players/default-player.jpg"
DEFAULT_TEAM_LOGO = "/NPL Logo.png"

ALIASES = {
    "mohammad-adil-alam": "mohammad-aadil-alam",
}

MANUAL_PROFILES = {
    "raymon-reifer": {
        "name": "Raymon Reifer",
        "team": "Pokhara Avengers",
        "team_slug": "pokhara-avengers",
        "role": "All-rounder",
        "image": DEFAULT_IMAGE,
        "is_international": True,
        "is_captain": False,
    },
}

TEAM_LOGOS = {
    "biratnagar-kings": "/images/teams/Biratnagar-Kings.png",
    "chitwan-rhinos": "/images/teams/Chitwan-Rhinos.png",
    "janakpur-bolts": "/images/teams/Janakpur-Bolts.png",
    "karnali-yaks": "/images/teams/Karnali-Yaks.png",
    "kathmandu-gurkhas": "/images/teams/Kathmandu-Gurkhas.png",
    "lumbini-lions": "/images/teams/Lumbini-Lions.png",
    "pokhara-avengers": "/images/teams/Pokhara-Avengers.png",
    "sudurpaschim-royals": "/images/teams/Sudurpaschim-Royals.png",
}

TEAM_SLUGS_BY_NAME = {
    "Biratnagar Kings": "biratnagar-kings",
    "Chitwan Rhinos": "chitwan-rhinos",
    "Janakpur Bolts": "janakpur-bolts",
    "Karnali Yaks": "karnali-yaks",
    "Kathmandu Gurkhas": "kathmandu-gurkhas",
    "Kathmandu Gorkhas": "kathmandu-gurkhas",
    "Lumbini Lions": "lumbini-lions",
    "Pokhara Avengers": "pokhara-avengers",
    "Sudurpaschim Royals": "sudurpaschim-royals",
}

SOCIAL_LINKS = {
    "facebook": "https://facebook.com/nplcricketnepal",
    "twitter": "https://twitter.com/nplcricketnepal",
    "instagram": "https://instagram.com/nplcricketnepal",
    "youtube": "https://youtube.com/@nplcricketnepal",
}

SOCIAL_ORDER = ["facebook", "twitter", "instagram", "youtube"]


def slugify(value: str) -> str:
    value = value.lower()
    value = re.sub(r"[^a-z0-9]+", "-", value)
    value = re.sub(r"-{2,}", "-", value)
    return value.strip("-")


def normalize_space(value: str | None) -> str:
    if not value:
        return ""
    return " ".join(value.split())


def asset_path(value: str | None) -> str:
    if not value or value.startswith("data:"):
        return DEFAULT_IMAGE
    if value.startswith("http://") or value.startswith("https://"):
        return value
    if value.startswith("../"):
        value = "/" + value[3:]
    elif value.startswith("./"):
        value = "/" + value[2:]
    elif not value.startswith("/"):
        value = "/" + value
    return quote(value, safe='/:._-~')


def public_url(value: str) -> str:
    if value.startswith("http://") or value.startswith("https://"):
        return value
    return f"{SITE_URL}{asset_path(value)}"


def team_slug_from_name(team_name: str) -> str | None:
    return TEAM_SLUGS_BY_NAME.get(normalize_space(team_name))


def build_image_index() -> dict[str, str]:
    image_index: dict[str, str] = {}
    for path in IMAGES_DIR.glob("*"):
        if path.is_file():
            image_index[slugify(path.stem)] = f"/images/players/{path.name}"

    image_index.update(
        {
            "dipendra-singh-airee": "/images/players/Dipendra Singh.webp",
            "aarif-sheikh": "/images/players/Aarif Sheikh.webp",
            "sompal-kami": "/images/players/Sompal Kami.webp",
            "karan-kc": "/images/players/Karan KC.webp",
        }
    )
    return image_index


def extract_team_name(path: Path, soup: BeautifulSoup) -> str:
    selectors = [".team-details h2", ".hero-content h1", "h1", "title"]
    for selector in selectors:
        node = soup.select_one(selector)
        if not node:
            continue
        text = normalize_space(node.get_text(" ", strip=True))
        for suffix in [" - Nepal Premier League", " Players", " Squad"]:
            if text.endswith(suffix):
                text = text[: -len(suffix)].strip()
        if text and text.lower() != "players":
            return text
    return path.stem.replace("-", " ").title()


def closest_player_card(node: Any) -> Any:
    current = node
    while current and getattr(current, "name", None) != "body":
        if "player-card" in current.get("class", []):
            return current
        current = current.parent
    return None


def parse_team_profiles() -> dict[str, dict[str, Any]]:
    image_index = build_image_index()
    profiles: dict[str, dict[str, Any]] = {}

    for team_file in sorted(TEAMS_DIR.glob("*.html")):
        soup = BeautifulSoup(team_file.read_text(encoding="utf-8"), "html.parser")
        team_name = extract_team_name(team_file, soup)
        team_slug = team_file.stem

        for link in soup.select('a[href^="/players/"]'):
            slug = link["href"].split("/players/", 1)[1].split("?", 1)[0].split("#", 1)[0].strip("/")
            if not slug:
                continue

            card = closest_player_card(link)
            if not card:
                continue

            name = normalize_space(card.select_one(".player-name").get_text(" ", strip=True) if card.select_one(".player-name") else "")
            role = normalize_space(card.select_one(".player-role").get_text(" ", strip=True) if card.select_one(".player-role") else "")
            if not role:
                badges = [
                    normalize_space(badge.get_text(" ", strip=True))
                    for badge in card.select(".role-badge")
                    if normalize_space(badge.get_text(" ", strip=True))
                ]
                role = " • ".join(badges) if badges else "Squad Player"

            image_node = card.select_one("img")
            image = asset_path(image_node["src"]) if image_node and image_node.get("src") else DEFAULT_IMAGE
            if image in {asset_path("/images/players/default-player.jpg"), asset_path("/images/Player.png")}:
                image = asset_path(image_index.get(slug, image_index.get(slugify(name), DEFAULT_IMAGE)))

            profiles[slug] = {
                "name": name or slug.replace("-", " ").title(),
                "slug": slug,
                "team": team_name,
                "team_slug": team_slug,
                "role": role,
                "image": image,
                "is_international": bool(card.select_one(".badge-intl")) or "international" in role.lower(),
                "is_captain": "captain" in role.lower(),
            }

    profiles.update(MANUAL_PROFILES)
    return profiles


def image_for_background(profile: dict[str, Any]) -> str:
    bg_candidates = [
        IMAGES_DIR / f"{profile['slug']}-bg.webp",
        IMAGES_DIR / f"{profile['slug']}-bg.jpg",
        IMAGES_DIR / f"{profile['slug']}-bg.png",
    ]
    for path in bg_candidates:
        if path.exists():
            return asset_path(f"/images/players/{path.name}")
    return profile["image"]


def title_for(name: str) -> str:
    return f"{name} | {SUBTITLE}"


def description_for(profile: dict[str, Any]) -> str:
    return (
        f"Explore the journey of {profile['name']}, a key {profile['team']} squad member in NPL 2026. "
        f"This guide covers the full profile, role, team context, playing style, and latest tournament updates."
    )


def intro_for(profile: dict[str, Any]) -> str:
    return (
        f"{profile['name']} is part of the <strong>{profile['team']}</strong> squad in the Nepal Premier League 2026. "
        f"Listed as <strong class=\"player-highlight\">{profile['role']}</strong>, {profile['name']} gives the team more depth and flexibility. "
        f"This profile page brings together team context, role details, and a quick overview in the same style used across major NPL player pages."
    )


def primary_role(profile: dict[str, Any]) -> str:
    role = profile["role"].lower()
    if "wicket" in role:
        return "wicket-keeper"
    if "all-rounder" in role:
        return "all-rounder"
    if "bowler" in role:
        return "bowler"
    if "batsman" in role or "batter" in role:
        return "batsman"
    return "player"


def strengths_for(profile: dict[str, Any]) -> list[tuple[str, str]]:
    role = primary_role(profile)
    if role == "bowler":
        return [
            ("Bowling Impact", "Provides bowling depth with the ability to handle important overs and support the team in pressure moments."),
            ("Match Control", "Adds value through discipline, clear role execution, and the ability to adapt to different batting matchups."),
            ("Team Balance", "Strengthens the overall bowling unit and gives the captain more tactical choices during a match."),
        ]
    if role == "all-rounder":
        return [
            ("Two-Way Value", "Contributes to both batting and bowling plans, which makes the squad more flexible during tight games."),
            ("Game Awareness", "Supports different match situations by adjusting tempo, reading conditions, and filling multiple roles."),
            ("Pressure Utility", "Helps the side stay balanced because the team can use the player in more than one phase of a T20 match."),
        ]
    if role == "wicket-keeper":
        return [
            ("Keeping Skills", "Adds value behind the stumps through clean takes, awareness, and support for the bowling unit."),
            ("Batting Support", "Offers batting depth and helps maintain balance in the XI with a dual-skill role."),
            ("Match Energy", "Brings communication, alertness, and game involvement throughout every over."),
        ]
    return [
        ("Batting Presence", "Adds batting depth and helps the team build or finish innings depending on the game situation."),
        ("Shot Selection", "Can support the lineup with intent, timing, and the ability to adapt against pace or spin."),
        ("Squad Balance", "Strengthens the batting group and gives the team extra stability across the tournament."),
    ]


def related_players(slug: str, profiles: dict[str, dict[str, Any]]) -> list[dict[str, Any]]:
    current = profiles[slug]
    teammates = [
        profile
        for other_slug, profile in profiles.items()
        if other_slug != slug and profile["team_slug"] == current["team_slug"]
    ]
    teammates.sort(key=lambda item: item["name"])
    return teammates[:4]


def table_one(profile: dict[str, Any]) -> str:
    international = "International" if profile["is_international"] else "Local Player"
    captaincy = "Captain" if profile["is_captain"] else "Squad Member"
    return f"""
                    <section class="table-section">
                        <div class="section-header">
                            <h2 class="section-title">NPL 2026 Profile Snapshot</h2>
                            <p class="section-description">
                                A quick overview of {profile['name']}'s role, current team situation, and profile status for the Nepal Premier League 2026 season.
                            </p>
                        </div>

                        <div class="table-container">
                            <table class="player-table">
                                <thead>
                                    <tr>
                                        <th>Category</th>
                                        <th>Detail</th>
                                        <th>Category</th>
                                        <th>Detail</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                        <td class="category-cell">Team</td>
                                        <td class="stat-cell">{profile['team']}</td>
                                        <td class="category-cell">Season</td>
                                        <td class="highlight-cell">NPL 2026</td>
                                    </tr>
                                    <tr>
                                        <td class="category-cell">Role</td>
                                        <td class="stat-cell">{profile['role']}</td>
                                        <td class="category-cell">Squad Status</td>
                                        <td class="stat-cell">{captaincy}</td>
                                    </tr>
                                    <tr>
                                        <td class="category-cell">Profile Type</td>
                                        <td class="stat-cell">Player Biography</td>
                                        <td class="category-cell">Category</td>
                                        <td class="stat-cell">{international}</td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                        <p class="overview-text">
                            This page is designed to match the main NPL player biography style while keeping the squad information easy to read and easy to navigate.
                        </p>
                    </section>
"""


def table_two(profile: dict[str, Any]) -> str:
    role = primary_role(profile)
    if role == "bowler":
        rows = [
            ("Bowling", "Key discipline", "Supports wicket-taking plans and over-by-over control."),
            ("Batting", "Lower-order value", "Adds extra depth when the batting lineup needs support."),
            ("Fielding", "Match support", "Helps improve overall intensity and pressure in the field."),
        ]
    elif role == "all-rounder":
        rows = [
            ("Batting", "Dual-role value", "Can contribute runs and support different phases of the innings."),
            ("Bowling", "Utility overs", "Gives the side another working option depending on conditions."),
            ("Fielding", "Balance", "Adds extra all-round value across the full match."),
        ]
    elif role == "wicket-keeper":
        rows = [
            ("Wicketkeeping", "Primary role", "Supports bowlers with glove work, movement, and awareness."),
            ("Batting", "Lineup depth", "Can help stabilize or accelerate the innings when required."),
            ("Field Presence", "Communication", "Keeps the side organized and involved throughout the match."),
        ]
    else:
        rows = [
            ("Batting", "Primary skill", "Adds intent and depth to the team's batting order."),
            ("Fielding", "Support value", "Improves pressure and intensity during key passages of play."),
            ("Team Role", "Squad balance", "Helps the side maintain flexible options across the tournament."),
        ]

    rows_html = "\n".join(
        f"""
                                    <tr>
                                        <td class="format-cell">{area}</td>
                                        <td class="stat-cell">{summary}</td>
                                        <td class="stat-cell">{impact}</td>
                                    </tr>
""" for area, summary, impact in rows
    )

    return f"""
                    <section class="table-section">
                        <div class="section-header">
                            <h2 class="section-title">Career Overview</h2>
                            <p class="section-description">
                                A role-based summary of how {profile['name']} fits into the team structure for the current season.
                            </p>
                        </div>

                        <div class="table-container">
                            <table class="player-table">
                                <thead>
                                    <tr>
                                        <th>Area</th>
                                        <th>Summary</th>
                                        <th>Impact on Team</th>
                                    </tr>
                                </thead>
                                <tbody>
{rows_html}
                                </tbody>
                            </table>
                        </div>
                    </section>
"""


def faq_markup(profile: dict[str, Any]) -> str:
    faqs = [
        (f"What team does {profile['name']} play for in NPL 2026?", f"{profile['name']} is listed in the {profile['team']} squad for the NPL 2026 season."),
        (f"What is {profile['name']}'s role?", f"The current squad role shown on this page is {profile['role']}."),
        (f"Is this page part of the official player profile section?", "Yes, this page is built to match the main player profile layout used on the site."),
        (f"Can I explore more players from {profile['team']}?", f"Yes, the related players section links to more {profile['team']} squad members."),
        (f"What should fans expect from {profile['name']} this season?", f"Fans can expect {profile['name']} to support {profile['team']} in the role of {profile['role']} during NPL 2026."),
    ]
    return "\n".join(
        f"""
                        <h4 class="faq-question">{question}</h4>
                        <p class="faq-answer">{answer}</p>
""" for question, answer in faqs
    )


def overview_markup(profile: dict[str, Any]) -> str:
    strengths = strengths_for(profile)
    strengths_html = "\n".join(
        f"""
                            <div class="strength-card">
                                <h3 class="strength-title">{title}</h3>
                                <p class="strength-description">{description}</p>
                            </div>
""" for title, description in strengths
    )

    return f"""
                    <h2 class="overview-title">{profile['name']} Player Profile</h2>

                    <div class="player-info">
                        <div class="info-card">
                            <h3 class="info-title">Squad Background</h3>
                            <p class="overview-text">
                                {profile['name']} is one of the listed players for <strong class="team-highlight">{profile['team']}</strong> in the Nepal Premier League 2026. This page follows the same layout as the site's main biography pages so fans can move smoothly between player profiles.
                            </p>
                        </div>

                        <div class="info-card">
                            <h3 class="info-title">Role in the Squad</h3>
                            <p class="overview-text">
                                The team page currently presents {profile['name']} as a <strong class="player-highlight">{profile['role']}</strong>. That role gives useful context for how {profile['name']} fits into selection plans, squad balance, and matchday combinations.
                            </p>
                        </div>
                    </div>

                    <h3 class="overview-subtitle">{profile['name']}'s Role in {profile['team']}</h3>
                    <p class="overview-text">
                        In a T20 league like the Nepal Premier League, every player adds value to the overall balance of the side. {profile['name']} strengthens <strong class="team-highlight">{profile['team']}</strong> by offering support in the role of <strong class="player-highlight">{profile['role']}</strong>. That helps the team stay flexible across different match conditions.
                    </p>

                    <h3 class="overview-subtitle">Domestic and Team Context</h3>
                    <p class="overview-text">
                        NPL squads are built to combine star power, squad depth, and tactical flexibility. {profile['name']} is part of that bigger setup, and this profile gives supporters a dedicated page to follow the player as the 2026 season continues.
                    </p>

                    <h3 class="overview-subtitle">{profile['name']} NPL 2026 Profile</h3>
                    <p class="overview-text">
                        For the <strong class="stat-highlight">2026 season</strong>, {profile['name']} appears in the <strong class="team-highlight">{profile['team']}</strong> squad list. The design, title format, and structure of this page now match the main player profile layout used elsewhere on the website.
                    </p>

{table_one(profile)}
{table_two(profile)}

                    <h3 class="overview-subtitle">Recent Updates and Achievements in 2026</h3>
                    <p class="overview-text">
                        This page is ready for future updates as more match data, performances, and tournament highlights are added. For now, it provides a clean player profile experience with role details, team identity, and a consistent NPL presentation.
                    </p>

                    <section class="strengths-section">
                        <div class="section-header">
                            <h2 class="section-title">Playing Style and Strengths</h2>
                            <p class="section-description">
                                A quick summary of the areas where {profile['name']} can help {profile['team']} during the tournament.
                            </p>
                        </div>

                        <div class="strengths-container">
{strengths_html}
                        </div>
                        <p class="overview-text">
                            These strengths help explain why {profile['name']} remains an important squad option for <strong class="team-highlight">{profile['team']}</strong>.
                        </p>
                    </section>

                    <h3 class="overview-subtitle">Future Prospects</h3>
                    <p class="overview-text">
                        If {profile['name']} continues to grow in this role and makes the most of NPL opportunities, there is room for even greater impact in future domestic seasons. Consistent squad visibility and strong performances can open bigger opportunities over time.
                    </p>

                    <div class="faq-section">
                        <h3 class="faq-title">Frequently Asked Questions</h3>
{faq_markup(profile)}
                    </div>
"""


def related_markup(profile: dict[str, Any], profiles: dict[str, dict[str, Any]]) -> str:
    cards = related_players(profile["slug"], profiles)
    cards_html = "\n".join(
        f"""
                        <a href="/players/{card['slug']}" class="related-player-card">
                            <h3 class="related-player-name">{card['name']}</h3>
                            <p class="related-player-team">{card['team']}</p>
                        </a>
""" for card in cards
    )
    return f"""
                    <div class="section-header">
                        <h2 class="section-title">Explore Other Players</h2>
                        <p class="section-description">
                            Discover more talented cricketers from the Nepal Premier League 2026.
                        </p>
                    </div>

                    <div class="related-players-grid">
{cards_html}
                    </div>
"""


def replace_style_background(html: str, background_image: str) -> str:
    pattern = r"(background-image:\s*url\(')([^']+)('\);)"
    return re.sub(pattern, rf"\1{background_image}\3", html, count=1)


def set_meta_content(soup: BeautifulSoup, *, attr_name: str, attr_value: str, content: str) -> None:
    tag = soup.find("meta", attrs={attr_name: attr_value})
    if tag:
        tag["content"] = content


def ensure_team_link_styles(soup: BeautifulSoup) -> None:
    style_tag = soup.find("style")
    if not style_tag:
        return

    css = style_tag.string or style_tag.get_text()
    if ".player-team-link" in css:
        return

    style_tag.string = css + """
        .player-team-link {
            display: inline-block;
            text-decoration: none;
            color: inherit;
        }

        .player-team-link:hover .team-name {
            color: #06b6d4;
        }
"""


def ensure_team_link_markup(soup: BeautifulSoup, team_slug: str | None) -> None:
    if not team_slug:
        return

    team_block = soup.select_one(".player-team")
    if team_block:
        href = f"/teams/{team_slug}"
        parent = team_block.parent
        if parent and getattr(parent, "name", None) == "a" and "player-team-link" in parent.get("class", []):
            parent["href"] = href
        else:
            team_link = soup.new_tag("a", href=href)
            team_link["class"] = ["player-team-link"]
            team_block.wrap(team_link)

    ensure_team_link_styles(soup)


def remove_view_all_players_button(soup: BeautifulSoup) -> None:
    for link in soup.find_all("a"):
        text = normalize_space(link.get_text(" ", strip=True))
        if text != "View All Players":
            continue

        parent = link.parent
        if parent and getattr(parent, "name", None) == "div":
            parent.decompose()
        else:
            link.decompose()


def ensure_real_social_links(soup: BeautifulSoup) -> None:
    for group in soup.select(".social-links, .footer-social"):
        anchors = [anchor for anchor in group.find_all("a", class_="social-link", recursive=False)]
        for index, anchor in enumerate(anchors):
            href = normalize_space(anchor.get("href"))
            if href and href != "javascript:void(0)":
                continue

            label = normalize_space(anchor.get("aria-label")).lower()
            key = next((name for name in SOCIAL_ORDER if name in label), None)
            if key is None and index < len(SOCIAL_ORDER):
                key = SOCIAL_ORDER[index]
                anchor["aria-label"] = key.title() if key != "youtube" else "YouTube"

            if key is None:
                continue

            anchor["href"] = SOCIAL_LINKS[key]
            anchor["target"] = "_blank"
            anchor["rel"] = "noopener noreferrer"


def render_generated_page(profile: dict[str, Any], profiles: dict[str, dict[str, Any]]) -> str:
    template_html = TEMPLATE_PATH.read_text(encoding="utf-8")
    soup = BeautifulSoup(template_html, "html.parser")

    title = title_for(profile["name"])
    description = description_for(profile)
    canonical = f"{SITE_URL}/players/{profile['slug']}"
    image_url = public_url(profile["image"])
    team_logo = TEAM_LOGOS.get(profile["team_slug"], DEFAULT_TEAM_LOGO)
    background_image = image_for_background(profile)

    if soup.title:
        soup.title.string = title

    set_meta_content(soup, attr_name="name", attr_value="description", content=description)
    set_meta_content(soup, attr_name="name", attr_value="keywords", content=f"{profile['name']}, {profile['name']} NPL 2026, {profile['team']}, Nepal Premier League")
    set_meta_content(soup, attr_name="property", attr_value="og:title", content=title)
    set_meta_content(soup, attr_name="property", attr_value="og:description", content=description)
    set_meta_content(soup, attr_name="property", attr_value="og:url", content=canonical)
    set_meta_content(soup, attr_name="property", attr_value="og:image", content=image_url)
    set_meta_content(soup, attr_name="name", attr_value="twitter:title", content=title)
    set_meta_content(soup, attr_name="name", attr_value="twitter:description", content=description)
    set_meta_content(soup, attr_name="name", attr_value="twitter:image", content=image_url)

    canonical_tag = soup.find("link", rel="canonical")
    if canonical_tag:
        canonical_tag["href"] = canonical

    structured = soup.find("script", attrs={"type": "application/ld+json"})
    if structured:
        structured.string = json.dumps(
            {
                "@context": "https://schema.org",
                "@type": "Person",
                "name": profile["name"],
                "memberOf": {"@type": "SportsTeam", "name": profile["team"]},
                "description": description,
                "url": canonical,
                "image": image_url,
            },
            ensure_ascii=False,
        )

    breadcrumb = soup.select_one(".breadcrumb-content")
    if breadcrumb:
        current_span = breadcrumb.find_all("span")[-1]
        current_span.string = profile["name"]

    player_title = soup.select_one(".player-title")
    if player_title:
        player_title.string = profile["name"]

    player_subtitle = soup.select_one(".player-subtitle")
    if player_subtitle:
        player_subtitle.string = SUBTITLE

    team_logo_tag = soup.select_one(".team-logo")
    if team_logo_tag:
        team_logo_tag["src"] = team_logo
        team_logo_tag["alt"] = profile["team"]

    team_name = soup.select_one(".team-name")
    if team_name:
        team_name.string = profile["team"]

    ensure_team_link_markup(soup, profile["team_slug"])
    remove_view_all_players_button(soup)
    ensure_real_social_links(soup)

    intro = soup.select_one(".intro-text")
    if intro:
        intro.clear()
        intro.append(BeautifulSoup(intro_for(profile), "html.parser"))

    overview = soup.select_one(".overview-content")
    if overview:
        overview.clear()
        overview.append(BeautifulSoup(overview_markup(profile), "html.parser"))

    related = soup.select_one(".related-players-content")
    if related:
        related.clear()
        related.append(BeautifulSoup(related_markup(profile, profiles), "html.parser"))

    body = soup.body
    if body and GENERATED_MARKER not in str(body):
        body.insert(0, BeautifulSoup(GENERATED_MARKER, "html.parser"))

    rendered = str(soup)
    rendered = replace_style_background(rendered, background_image)
    return rendered


def render_redirect_page(target_slug: str) -> str:
    target_url = f"/players/{target_slug}"
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Redirecting...</title>
    <meta name="robots" content="noindex, follow">
    <meta http-equiv="refresh" content="0; url={target_url}">
    <link rel="canonical" href="{SITE_URL}{target_url}">
    <script>window.location.replace("{target_url}" + window.location.search + window.location.hash);</script>
</head>
<body>
    {GENERATED_MARKER}
    <p>Redirecting to <a href="{target_url}">{target_url}</a>.</p>
</body>
</html>
"""


def normalize_existing_profile(path: Path) -> None:
    html = path.read_text(encoding="utf-8")
    if GENERATED_MARKER in html:
        return

    soup = BeautifulSoup(html, "html.parser")
    player_title = soup.select_one(".player-title")
    if not player_title:
        return

    name = normalize_space(player_title.get_text(" ", strip=True))
    title = title_for(name)

    if soup.title:
        soup.title.string = title

    set_meta_content(soup, attr_name="property", attr_value="og:title", content=title)
    set_meta_content(soup, attr_name="name", attr_value="twitter:title", content=title)

    subtitle = soup.select_one(".player-subtitle")
    if subtitle:
        subtitle.string = SUBTITLE

    team_name = soup.select_one(".team-name")
    team_slug = team_slug_from_name(team_name.get_text(" ", strip=True)) if team_name else None
    ensure_team_link_markup(soup, team_slug)
    remove_view_all_players_button(soup)
    ensure_real_social_links(soup)

    path.write_text(str(soup), encoding="utf-8")


def normalize_all_player_social_links() -> None:
    for path in PLAYERS_DIR.glob("*.html"):
        html = path.read_text(encoding="utf-8")
        soup = BeautifulSoup(html, "html.parser")
        before = str(soup)
        ensure_real_social_links(soup)
        after = str(soup)
        if after != before:
            path.write_text(after, encoding="utf-8")


def main() -> None:
    profiles = parse_team_profiles()

    for alias_slug, target_slug in ALIASES.items():
        (PLAYERS_DIR / f"{alias_slug}.html").write_text(render_redirect_page(target_slug), encoding="utf-8")

    for path in PLAYERS_DIR.glob("*.html"):
        normalize_existing_profile(path)

    for slug, profile in sorted(profiles.items()):
        if (PLAYERS_DIR / f"{slug}.html").exists():
            current = (PLAYERS_DIR / f"{slug}.html").read_text(encoding="utf-8")
            if GENERATED_MARKER not in current:
                continue
        profile["slug"] = slug
        (PLAYERS_DIR / f"{slug}.html").write_text(render_generated_page(profile, profiles), encoding="utf-8")

    normalize_all_player_social_links()


if __name__ == "__main__":
    main()
